config/routes.rb
Multichilds::Application.routes.draw do

  resources :icons
  resources :dishes
  root :to => 'icons#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  #assosiation for nested model
  has_many :dishes_icons
  # Must add "allow_destroy: true" in the line below to provide remove functionality
  accepts_nested_attributes_for :dishes_icons, allow_destroy: true

  # add :assosiation_attributes to attr_accessible to acces nested model attributes
  attr_accessible :name, :dishes_icons_attributes
end

app/models/dishes_icon.rb
class DishesIcon < ActiveRecord::Base
  belongs_to :dish
  belongs_to :icon
  attr_accessible :dish_id, :icon_id
end

app/models/icon.rb
class Icon < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_filter :load_dish, only: [:edit, :update, :destroy]

  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
  end
# Multi Fields generation in nested form --> Start
  def new
    @dish = Dish.new
    @dish_icons = @dish.dishes_icons.build
  end

  def edit
    @dish_icons = @dish.dishes_icons
    @dish_icons ||= @dish.dishes_icons.build
  end
# Multi Fields generation in nested form --> End
  def create
    @dish = Dish.new(params[:dish])
    if @dish.save
      redirect_to @dish, notice: 'Dish was successfully created.'
    else
      render action: "new"
    end
  end

  def update
      if @dish.update_attributes(params[:dish])
        redirect_to @dish, notice: 'Dish was successfully updated.'
      else
        render action: "edit"
      end
  end

  def destroy
    @dish.destroy
    redirect_to dishes_url
  end

  private

  def load_dish
    @dish = Dish.find(params[:id])
  end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @icons }
    end
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
    @icon = Icon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @icon }
    end
  end

  # GET /icons/new
  # GET /icons/new.json
  def new
    @icon = Icon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @icon }
    end
  end

  # GET /icons/1/edit
  def edit
    @icon = Icon.find(params[:id])
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new(params[:icon])

    respond_to do |format|
      if @icon.save
        format.html { redirect_to @icon, notice: 'Icon was successfully created.' }
        format.json { render json: @icon, status: :created, location: @icon }
      else
        format.html { render action: "new" }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /icons/1
  # PUT /icons/1.json
  def update
    @icon = Icon.find(params[:id])

    respond_to do |format|
      if @icon.update_attributes(params[:icon])
        format.html { redirect_to @icon, notice: 'Icon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon = Icon.find(params[:id])
    @icon.destroy

    respond_to do |format|
      format.html { redirect_to icons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/dishes/_dishes_icon_fields.html.erb
<div class="fields">
  <%= f.select :icon_id, Icon.all.collect {|icon| [icon.name, icon.id]} %>
  <%= link_to_remove_fields "remove", f %>
</div>
 
  

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <!-- Multi Fields generation in nested form Start  -->
  <!-- Link to add Nested attributes -->
  <p><%= link_to_add_fields "Add Dish Icon", f, :dishes_icons %></p>
  <div class="dishes-icons">
    <!-- All nested fields Loop and partial,  the div below with class named "all_nested_fields" will be used in js method add_fields -->
    <div class="all_nested_fields" > 
      <%= f.fields_for :dishes_icons do |dishes_icon|%>
       <%= render "dishes_icon_fields", :f => dishes_icon, formats: [:html] %>
      <%end%>
    </div>
  </div>
  <!-- Multi Fields generation in nested form End  --> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.name %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dish.name %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/icons/_form.html.erb
<%= form_for(@icon) do |f| %>
  <% if @icon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
      <% @icon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/icons/edit.html.erb
<h1>Editing icon</h1>

<%= render 'form' %>

<%= link_to 'Show', @icon %> |
<%= link_to 'Back', icons_path %>

app/views/icons/index.html.erb
<h1>Listing icons</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @icons.each do |icon| %>
  <tr>
    <td><%= icon.name %></td>
    <td><%= link_to 'Show', icon %></td>
    <td><%= link_to 'Edit', edit_icon_path(icon) %></td>
    <td><%= link_to 'Destroy', icon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Icon', new_icon_path %>

app/views/icons/new.html.erb
<h1>New icon</h1>

<%= render 'form' %>

<%= link_to 'Back', icons_path %>

app/views/icons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @icon.name %>
</p>


<%= link_to 'Edit', edit_icon_path(@icon) %> |
<%= link_to 'Back', icons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multichilds</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>


<%= link_to 'Icons', icons_path %>
<%= link_to 'Dishes', dishes_path %>
<%= yield %>

</body>
</html>